replicaCount: 2

image:
  repository: perception-inference
  tag: local
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

mlflow:
  trackingUri: "http://mlflow-server.mlops.svc.cluster.local:5000"

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "2"
    memory: "4Gi"

livenessProbe:
  path: /health
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 10
